### ISSUE TITLE
The fetch window crashes all the time

### ISSUE THREAD

**Issue by micsova** [hapiest-team/hapiest#23] opened 2017-11-27 19:16 UTC

**Comment by jkarns275** [comment] 2017-12-05 06:00
Needs further testing to verify the issue is gone @micsova @BenjiCaro

**Comment by BenjiCaro** [comment] 2017-12-08 19:43
@jkarns275 Was not solved by 97213672fb30f7ccb95aed997c9b0374ce46fdc6, resolved by 8e91e515e4a16dddf8e889d30840415a8a1ea055: the worker thread was being closed twice. Needs to be verified through testing

**Comment by jkarns275** [comment] 2017-12-14 19:11
Whatever was causing these crashes has been fixed. Other bugs should have their own issue opened

**Closed by jkarns275** 2017-12-14 19:11 UTC
Labels: bug, feature
